Update cd-action.yml

diff --git a/.github/workflows/cd-action.yml b/.github/workflows/cd-action.yml
--- a/.github/workflows/cd-action.yml
+++ b/.github/workflows/cd-action.yml
@@ -21,6 +21,15 @@ jobs:
             sudo apt update -y
             curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
             sudo apt install -y nodejs
+            # Check if pm2 is installed
+            if ! command -v pm2 &> /dev/null
+            then
+            echo "PM2 not found. Installing..."
+            # Install pm2 globally with npm
+            sudo npm install -g pm2
+            echo "PM2 installed successfully."
+            else
+            echo "PM2 is already installed: $(pm2 -v)"
             if [ ! -d "/var/www/myapp/.git" ]; then
               sudo mkdir -p /var/www/myapp
               sudo chown -R $USER:$USER /var/www/myapp
